name: Build & Deploy to GitHub Pages - Angular

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set git user
        run: |
          git config --global user.email "jhanmaquera@gmail.com"
          git config --global user.name "AbelRM"

      - name: Deploy to Github pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npx ng deploy --base-href=/app-angular-deploy/
        # npm run ng -- deploy --repo=https://github.com/AbelRM/app-angular-deploy.git --name="AbelRM" --email="jhanmaquera@gmail.com" --base-href=/app-angular-deploy/
